<?php require __DIR__.'/lib.php'; require_login(); $slug=$_GET['slug']??''; $inv=load_invitation($slug); if(!$inv){http_response_code(404);exit('Undangan tidak ditemukan');} $scan=scan_template($inv['template']);
if($_SERVER['REQUEST_METHOD']==='POST'){
 $inv['title']=trim($_POST['title']??$inv['title']); $inv['status']=$_POST['status']??'draft';
 $reps=[]; $from=$_POST['from']??[]; $to=$_POST['to']??[]; foreach($from as $i=>$f){$f=(string)$f;$v=(string)($to[$i]??'');if($f!=='' && $v!=='' && $v!==$f)$reps[]=['from'=>$f,'to'=>$v];}
 // uploads map to replacement indexes
 foreach($_FILES['upload']['name']??[] as $key=>$name){ if(!$name||($_FILES['upload']['error'][$key]??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)continue; $ext=strtolower(pathinfo($name,PATHINFO_EXTENSION)); if(!in_array($ext,['jpg','jpeg','png','webp','gif','mp4','mp3','wav']))continue; $dir=__DIR__.'/storage/uploads/'.$inv['slug']; if(!is_dir($dir))mkdir($dir,0775,true); $safe=uniqid('media_',true).'.'.$ext; move_uploaded_file($_FILES['upload']['tmp_name'][$key],$dir.'/'.$safe); $public='storage/uploads/'.$inv['slug'].'/'.$safe; $source=$_POST['upload_from'][$key]??''; if($source!==''){$reps=array_values(array_filter($reps,fn($r)=>$r['from']!==$source));$reps[]=['from'=>$source,'to'=>$public];} }
 $inv['replacements']=$reps; save_invitation($inv); header('Location: editor.php?slug='.urlencode($slug).'&saved=1');exit;
}
$existing=[]; foreach($inv['replacements']??[] as $r)$existing[$r['from']]=$r['to'];
$common=['Habib & Adiba','Habib &amp; Adiba','Habib Yulianto','Adiba Putri Syakila','28. 12. 2026','Nama Tamu'];
function rows($items,$existing,$type){foreach($items as $x){$val=$existing[$x]??$x; echo '<div class="edit-row"><div class="original"><span>'.e(strtoupper($type)).'</span><code>'.e(mb_strimwidth($x,0,110,'…')).'</code></div><input type="hidden" name="from[]" value="'.e($x).'">'; if($type==='text')echo '<textarea name="to[]" rows="2">'.e($val).'</textarea>';else echo '<input name="to[]" value="'.e($val).'">'; if(in_array($type,['image','video'])){$key=sha1($x);echo '<input type="hidden" name="upload_from['.$key.']" value="'.e($x).'"><label class="upload-mini">Upload<input type="file" name="upload['.$key.']" accept="image/*,video/*"></label>';}else echo '<span></span>'; echo '</div>';}}
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Editor</title><link rel="stylesheet" href="assets/admin.css"></head><body><aside class="sidebar"><div class="logo">DW</div><nav><a href="index.php">Dashboard</a><a href="templates.php">Template</a><a class="active" href="#">Editor</a><a href="logout.php">Keluar</a></nav></aside><main class="app editor-app"><header><div><h1><?=e($inv['title'])?></h1><p>Template: <?=e(templates()[$inv['template']]['name'])?> · URL: /<?=e($inv['slug'])?></p></div><div class="header-actions"><a class="btn" target="_blank" href="view.php?slug=<?=urlencode($slug)?>">Preview penuh</a></div></header><?php if(isset($_GET['saved'])):?><div class="success">Perubahan tersimpan.</div><?php endif?><div class="editor-grid"><form class="panel editor-form" method="post" enctype="multipart/form-data"><div class="sticky-tools"><label>Judul<input name="title" value="<?=e($inv['title'])?>"></label><label>Status<select name="status"><option value="draft" <?=$inv['status']==='draft'?'selected':''?>>Draft</option><option value="published" <?=$inv['status']==='published'?'selected':''?>>Published</option></select></label><button class="btn primary">Simpan Perubahan</button></div><div class="hint"><b>Cara edit:</b> bagian kiri adalah nilai asli template, bagian kanan isi baru. Biarkan sama kalau tidak ingin diubah.</div><details open><summary>📝 Semua Teks <b><?=count($scan['texts'])?></b></summary><div class="rows"><?php rows($scan['texts'],$existing,'text')?></div></details><details><summary>🖼️ Semua Gambar <b><?=count($scan['images'])?></b></summary><div class="rows"><?php rows($scan['images'],$existing,'image')?></div></details><details><summary>🔗 Semua Link <b><?=count($scan['links'])?></b></summary><div class="rows"><?php rows($scan['links'],$existing,'link')?></div></details><details><summary>🎬 Semua Video <b><?=count($scan['videos'])?></b></summary><div class="rows"><?php rows($scan['videos'],$existing,'video')?></div></details></form><section class="phone-preview"><div class="phone"><iframe id="preview" src="view.php?slug=<?=urlencode($slug)?>"></iframe></div><p>Preview setelah disimpan</p></section></div></main></body></html>
